apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qfbt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-qfbt@sha256:694bbaabaef197975687bcef88b1f3a51acb9c1722030cd63cb4648699b025bb
        name: my-nodejs
        resources: {}
status: {}
